// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://juvztbjqddbaiareqqcy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1dnp0YmpxZGRiYWlhcmVxcWN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4Nzk5OTAsImV4cCI6MjA3MTQ1NTk5MH0.waqqvyNWZSooNoajD6gc5fPO2rEtNo6k2qw8m6XcnFg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});